language: python
python:
    - '2.7'
addons:
    apt:
        packages:
            - python-sqlite
            - python-tz
            - supybot
script:
    - echo $TRAVIS_PYTHON_VERSION
    - cd .. && supybot-test Encyclopedia
